version: '3.8'

services:

  backend:
    build: ./BACKEND
    container_name: backend-ibrt
    env_file:
     - ./BACKEND/.env
    ports:
      - 2500:2500
    volumes:
      - ./BACKEND:/app
    command: npm start
  
  frontend:
    build: ./FRONTEND/pagina_iglesia
    container_name: frontend-ibrt
    ports:
      - 80:80
    volumes:
      - ./FRONTEND/pagina_iglesia:/usr/share/nginx/html
